name: ci

on:
  workflow_dispatch:

  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '50 * * * *'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.number || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt,clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy
      - run: cargo +nightly fmt
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose
      - name: Run
        run: cargo run
      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update yaml"
